# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d90738961caa74ac8d09d9ff9b7a27387f66318d3c0b6b4d6a782bec6a65607a58ec2cc70afec71cc2198fc756ee075182ca7d79f1ec57aedaefa4f038f3f7ef

test:
  secret_key_base: b757f0302d3493ee7cc39fadf99c949dd49bcdc01280d518549c010ed5e70a0782334ffe912b2f99010d5ef67dfeac6a57ed3db441222c3d51549822e4638626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
